# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: deployment-bridge

on:
  push:
    branches: [ master ]

jobs:
  release-and-deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Retrieve version
      run: echo "::set-env name=TAG_NAME::v$(head -n 1 dist/latest.yml | sed 's/version:\s//')"

    - name: Create Release and tag
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.TAG_NAME }}

    - name: Deploy to AWS S3
      run: aws s3 cp --recursive dist ${{ secrets.AWS_S3_BUCKET_BRIDGE }}
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        